language: android
android:
 components:
    - tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository

jdk: oraclejdk8

script:
  - mvn -q android:lint
  - mvn -q test
  - ./gradlew build
